project_id = "kgazsoccrtmhturhxggi"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://kgazsoccrtmhturhxggi.supabase.co"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_captcha_enabled = false
security_update_password_require_reauthentication = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.waf-monitor]
verify_jwt = false

[functions.simulate-traffic]
verify_jwt = false

[functions.ai-anomaly-detector]
verify_jwt = false

[functions.compliance-reporter]
verify_jwt = false

[functions.siem-integrator]
verify_jwt = false

[functions.inline-waf]
verify_jwt = false

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"

[analytics]
enabled = false

[functions]
port = 54326

[realtime]
enabled = true
port = 54327

[edge_runtime]
port = 54328