global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'waf-metrics'
    static_configs:
      - targets: ['ana-waf-dev:9090']
    metrics_path: /waf/metrics
    scrape_interval: 5s

  - job_name: 'waf-status'
    static_configs:
      - targets: ['ana-waf-dev:9090']
    metrics_path: /waf/status
    scrape_interval: 30s