// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgazsoccrtmhturhxggi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnYXpzb2NjcnRtaHR1cmh4Z2dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NTI4MTEsImV4cCI6MjA3NDIyODgxMX0.rwvIWWqhCoZZgB4n92GUpBGvsYXnPAKGOp3-likDrD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});